### ISSUE TITLE
app freeze when user don't let access to camera / gallery

### ISSUE THREAD

**Issue by jerem17** [flutter-form-builder-ecosystem/form_builder_image_picker#2]
Hello,

when requesting authorization from the camera, if the user refuses, the application freezes completely. How can I handle the exception on my side?

![image](https://user-images.githubusercontent.com/36238691/105158083-df0ff700-5b0d-11eb-8f1b-48777b950e00.png)

**Comment by ahmedoid** [comment]
Readme
Changelog
Example
Installing
Versions
Scores
Image Picker plugin for Flutter 
pub package

A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.

Installation 
First, add image_picker as a dependency in your pubspec.yaml file.

iOS 
Add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

NSPhotoLibraryUsageDescription - describe why your app needs permission for the photo library. This is called Privacy - Photo Library Usage Description in the visual editor.
NSCameraUsageDescription - describe why your app needs access to the camera. This is called Privacy - Camera Usage Description in the visual editor.
NSMicrophoneUsageDescription - describe why your app needs access to the microphone, if you intend to record videos. This is called Privacy - Microphone Usage Description in the visual editor.
Android 
API < 29
No configuration required - the plugin should work out of the box.

API 29+
Add android:requestLegacyExternalStorage="true" as an attribute to the <application> tag in AndroidManifest.xml. The attribute is false by default on apps targeting Android Q.

https://pub.dev/packages/image_picker

**Comment by jerem17** [comment]
yes i know, but if I deny access to the camera when it ask me, it crashes

**Comment by dav01it** [comment]
Same if you use the web as device: it works but if you press cancel upon the file picker window it freezes.

**Comment by ahmednfwela** [comment]
solved in #18

**Comment by tonypottera24** [comment]
![Screen Shot 2022-07-21 at 3 27 54 PM](https://user-images.githubusercontent.com/3013707/180144472-7c951933-f7d3-45b7-9383-dd4a96e3e918.png)
Sorry that I'm using iOS simulator and it still shows the same error

**Comment by deandreamatias** [comment]
@tonypottera24 Your app freeze in profile or release mode?
If yes, please a new bug issue

**Comment by tonypottera24** [comment]
@deandreamatias thank you for helping me.
It only freezes in profile mode.
